[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
sea-orm = { version = "2.0.0-rc.6" }
chrono = { version = "0.4.41", features = ["serde"]}
serde_json = "1.0"