# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sponsor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sponsor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsponsor.proto\x12\x07sponsor\"\xb6\x01\n\x12ProcessGameRequest\x12(\n\x04init\x18\x01 \x01(\x0b\x32\x18.sponsor.GameInitRequestH\x00\x12\'\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\x15.sponsor.PlayerActionH\x00\x12\'\n\x07\x63ontrol\x18\x03 \x01(\x0b\x32\x14.sponsor.GameControlH\x00\x12\x14\n\nconnection\x18\x04 \x01(\x08H\x00\x42\x0e\n\x0crequest_type\"\xba\x01\n\x13ProcessGameResponse\x12\x32\n\rinit_response\x18\x01 \x01(\x0b\x32\x19.sponsor.GameInitResponseH\x00\x12\x30\n\x0cstate_update\x18\x02 \x01(\x0b\x32\x18.sponsor.GameStateUpdateH\x00\x12,\n\nend_status\x18\x03 \x01(\x0b\x32\x16.sponsor.GameEndStatusH\x00\x42\x0f\n\rresponse_type\"$\n\x0fGameInitRequest\x12\x11\n\tgame_type\x18\x01 \x01(\t\"\x1e\n\x0cPlayerAction\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\"c\n\x0bGameControl\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .sponsor.GameControl.ControlType\"$\n\x0b\x43ontrolType\x12\t\n\x05PAUSE\x10\x00\x12\n\n\x06RESUME\x10\x01\"m\n\x10GameInitResponse\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.sponsor.GameInitResponse.ResultType\"%\n\nResultType\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\"C\n\x0fGameStateUpdate\x12\r\n\x05state\x18\x01 \x01(\t\x12\x0f\n\x07is_over\x18\x02 \x01(\x08\x12\x10\n\x08i_player\x18\x03 \x01(\x05\" \n\rGameEndStatus\x12\x0f\n\x07payoffs\x18\x02 \x03(\x02\x32^\n\x0eSponsorService\x12L\n\x0bProcessGame\x12\x1b.sponsor.ProcessGameRequest\x1a\x1c.sponsor.ProcessGameResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sponsor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSGAMEREQUEST']._serialized_start=27
  _globals['_PROCESSGAMEREQUEST']._serialized_end=209
  _globals['_PROCESSGAMERESPONSE']._serialized_start=212
  _globals['_PROCESSGAMERESPONSE']._serialized_end=398
  _globals['_GAMEINITREQUEST']._serialized_start=400
  _globals['_GAMEINITREQUEST']._serialized_end=436
  _globals['_PLAYERACTION']._serialized_start=438
  _globals['_PLAYERACTION']._serialized_end=468
  _globals['_GAMECONTROL']._serialized_start=470
  _globals['_GAMECONTROL']._serialized_end=569
  _globals['_GAMECONTROL_CONTROLTYPE']._serialized_start=533
  _globals['_GAMECONTROL_CONTROLTYPE']._serialized_end=569
  _globals['_GAMEINITRESPONSE']._serialized_start=571
  _globals['_GAMEINITRESPONSE']._serialized_end=680
  _globals['_GAMEINITRESPONSE_RESULTTYPE']._serialized_start=643
  _globals['_GAMEINITRESPONSE_RESULTTYPE']._serialized_end=680
  _globals['_GAMESTATEUPDATE']._serialized_start=682
  _globals['_GAMESTATEUPDATE']._serialized_end=749
  _globals['_GAMEENDSTATUS']._serialized_start=751
  _globals['_GAMEENDSTATUS']._serialized_end=783
  _globals['_SPONSORSERVICE']._serialized_start=785
  _globals['_SPONSORSERVICE']._serialized_end=879
# @@protoc_insertion_point(module_scope)
