# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: sponsor.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import sponsor_pb2


class SponsorServiceBase(abc.ABC):

    @abc.abstractmethod
    async def ProcessGame(self, stream: 'grpclib.server.Stream[sponsor_pb2.ProcessGameRequest, sponsor_pb2.ProcessGameResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/sponsor.SponsorService/ProcessGame': grpclib.const.Handler(
                self.ProcessGame,
                grpclib.const.Cardinality.STREAM_STREAM,
                sponsor_pb2.ProcessGameRequest,
                sponsor_pb2.ProcessGameResponse,
            ),
        }


class SponsorServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.ProcessGame = grpclib.client.StreamStreamMethod(
            channel,
            '/sponsor.SponsorService/ProcessGame',
            sponsor_pb2.ProcessGameRequest,
            sponsor_pb2.ProcessGameResponse,
        )
